name: dpro
description: A sample command-line application.
version: 0.0.2
homepage: https://figbox.com

environment:
  sdk: '>=2.14.3 <3.0.0'


dependencies:
  path: ^1.8.0
  sprintf: ^6.0.0
  auto_exporter: ^1.2.4

dev_dependencies:
  build_runner: ^2.1.0
  build_test: ^2.1.0
  lints: ^1.0.0
  test: ^1.16.0

