name: dpro
description: A tool to transform programing langrage. it can transform algorithm to Python and Java now. !! it is a lowcode develop engine.
version: 0.3.1
homepage: https://github.com/normidar/DPro

environment:
  sdk: '>=2.14.3 <3.0.0'


dependencies:
  path: ^1.8.0
  sprintf: ^6.0.0

dev_dependencies:
  auto_exporter: ^1.4.0 # please use Dart Barrel File Generator
  build_runner: ^2.1.7
  build_test: ^2.1.5
  lints: ^1.0.0
  test: ^1.16.0